package com.crewman.hibernateproject;
// Generated Jun 3, 2013 12:09:10 AM by Hibernate Tools 3.2.1.GA



/**
 * Devices generated by hbm2java
 */
public class Devices  implements java.io.Serializable {


     private String regId;

    public Devices() {
    }

    public Devices(String regId) {
       this.regId = regId;
    }
   
    public String getRegId() {
        return this.regId;
    }
    
    public void setRegId(String regId) {
        this.regId = regId;
    }




}


