package com.crewman.hibernateproject;
// Generated May 22, 2013 3:03:03 PM by Hibernate Tools 3.2.1.GA



/**
 * IncidentPicture generated by hbm2java
 */
public class IncidentPicture  implements java.io.Serializable {


     private Integer id;
     private IncidentMsg incidentMsg;
     private String picture;

    public IncidentPicture() {
    }

    public IncidentPicture(IncidentMsg incidentMsg, String picture) {
       this.incidentMsg = incidentMsg;
       this.picture = picture;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public IncidentMsg getIncidentMsg() {
        return this.incidentMsg;
    }
    
    public void setIncidentMsg(IncidentMsg incidentMsg) {
        this.incidentMsg = incidentMsg;
    }
    public String getPicture() {
        return this.picture;
    }
    
    public void setPicture(String picture) {
        this.picture = picture;
    }
    @Override
    public String toString(){
        return id +", " + picture;
    }


}


